<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WpfMusicEditor.Support\WpfMusicEditor.Support.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
      <PackageReference Include="NAudio" Version="2.2.1" />
      <PackageReference Include="NAudio.Lame" Version="2.1.0" />
      <PackageReference Include="Whisper.net" Version="1.9.0" />
      <PackageReference Include="Whisper.net.Runtime" Version="1.9.0" />
      <PackageReference Include="Whisper.net.Runtime.Cuda" Version="1.9.0" />
    </ItemGroup>
</Project>
